---
hostname: landing.p4.greenpeace.org
environment: production
api: >
  https://www.greenpeace.org/international/wp-content/
  themes/planet4-master-theme/templates/countries.json
ingress:
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip
  hosts:
    - name: www.greenpeace.org
    - name: www.greenpeace.org
      path: global
    - name: landing.p4.greenpeace.org
      path: global
    - name: stage.landing.p4.greenpeace.org
    - name: stage.landing.p4.greenpeace.org
      path: global
