---
image:
  repository: greenpeaceinternational/p4-landing-page
openresty:
  geoip:
    enabled: true
    accountid: ""
    license: ""
pagespeed:
  enabled: false
ingress:
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip
