---
image:
  repository: greenpeaceinternational/p4-landing-page
geoip:
  enabled: true
pagespeed:
  enabled: false
ingress:
  annotations:
    - "traefik.frontend.rule.type: PathPrefixStrip"
    - "traefik.frontend.rule=HostRegexp:{catchall:.*}"
    - "traefik.ingress.kubernetes.io/priority: '1'"
