---
hostname: dev.landing.p4.greenpeace.org
environment: development
api: >
  https://www-stage.greenpeace.org/international/
  wp-content/themes/planet4-master-theme/templates/countries.json
static: >
  https://dev.landing.p4.greenpeace.org/global/static/
ingress:
  hosts:
    - name: dev.landing.p4.greenpeace.org
    - name: dev.landing.p4.greenpeace.org
      path: global
openresty:
  cloudflare:
    enabled: false
