---
hostname: www-dev.greenpeace.org
environment: development
api: >
  https://www-stage.greenpeace.org/international/
  wp-content/themes/planet4-master-theme/templates/countries.json
static: >
  https://www-dev.greenpeace.org/global/static/
ingress:
  hosts:
    - name: www-dev.greenpeace.org
      path: global
    - name: landing-dev.greenpeace.org
    - name: landing-dev.greenpeace.org
      path: global
openresty:
  cloudflare:
    enabled: true
